### ISSUE TITLE
SUGESSTION: TODO List

### ISSUE THREAD

**Issue by brenobaise** [UOW-Computing/Emperor#7]
# TODO LIST

Please feel free to add more to the TODO list here.

This is a work in progress file. Any suggestions you might want to introduce into the bot, give it a title and a much better description unlike the ones down here. - Breno

:o - nuke

## Missing Documentation for BOT setup
Anybody can do the documentation on how to get `TOKEN`, `GUILD ID`, `CHANNEL ID`, `STAFF ID ?`
[Missing Doc Issue](https://github.com/UOW-Computing/Emperor/issues/29)

## Add `/help`
The command should output an embed showcasing the cogs as different fields, with the values being the different commands that the cog has under.

This may use to overload the fields, therefore using description would be better.

## Add `/tutorials`
Just a replacement of the already existing `/tutorials` command, should be a group where `/tutorials git` would only showcase git tutorial.

## Example of a suggestion 
Keep the title short and brief, no big phrases. 
Use the body to elaborate on the context of your suggestion. 
Try to be descriptive and stick to your objective.
You can use this [Github Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) on how to style your text.

## Code in suggestions
Any code that you wish to share, please use code blocks.
\`code here\` is for single line codes: `code here`
\`\`\` 
code
here
\`\`\`

```
code
here
```
Above is an example of for multiple lines.

Always remember to double-check what you are posting before doing so. 

*edited by @Nukestye*

**Comment by Nukestye** [comment]
Closing this Issue, as it has accomplished whatever it's purpose was.
